// <auto-generated />
namespace Doozestan.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addsomecolumn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addsomecolumn));
        
        string IMigrationMetadata.Id
        {
            get { return "201612181751443_add some column"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
